name: Build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: Build executable
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          check-latest: true

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Download DLL needed for opencv
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          curl -s -L "http://ciscobinary.openh264.org/openh264-1.8.0-win64.dll.bz2" | bzip2 -d > "openh264-1.8.0-win64.dll"

      - name: Install system dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install --yes libcairo2-dev

      - name: Build executable
        run: tox -e package

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: phff-${{ matrix.os }}
          path: dist/
